export const actions = {
  BULK_DELETE_PHOTOS_SUCCESS: 'delete-photos-success',
  BULK_DELETE_PHOTOS: 'delete-photos',
  BULK_EDIT_PHOTOS_SUCCESS: 'bulk-edit-photos-success',
  BULK_EDIT_PHOTOS: 'bulk-edit-photos',
  CREATE_PERSON_SUCCESS: 'create-person-success',
  CREATE_PERSON: 'create-person',
  DELETE_PERSON_SUCCESS: 'delete-person-success',
  DELETE_PERSON: 'delete-person',
  EXPORT_PHOTOS_SUCCESS: 'export-photos-success',
  EXPORT_PHOTOS: 'export-photos',
  FILEPATHS_OBTAINED: 'filepaths-obtained',
  INITIALIZE_PHOTO_MANAGER: 'initialize-photo-manager',
  MOVE_FILES_SUCCESS: 'move-files-success',
  MOVE_FILES: 'move-files',
  OPEN_RECENT_DIRECTORY: 'open-recent-directory',
  SAVE_PHOTO_MANAGER: 'save-photo-manager',
  SCRUB_EXIF_DATA_SUCCES: 'scrub-exif-data-success',
  SCRUB_EXIF_DATA: 'scrub-exif-data',
  SELECT_DIRECTORY: 'select-directory',
  SELECT_EXPORT_DIRECTORY_SUCCESS: 'select-export-directory-success',
  SELECT_EXPORT_DIRECTORY: 'select-export-directory',
  SELECT_MOVE_TARGET_FAILURE: 'select-move-target-failure',
  SELECT_MOVE_TARGET_SUCCESS: 'select-move-target-success',
  SELECT_MOVE_TARGET: 'select-move-target',
  UPDATE_PERSON_SUCCESS: 'update-person-success',
  UPDATE_PERSON: 'update-person',
  UPDATE_PHOTO_DATA_COMPLETE: 'update-photo-data-complete',
  UPDATE_PHOTO_DATA: 'update-photo-data',
};

export default null;
