export const actions = {
  BULK_EDIT_PHOTOS: 'bulk-edit-photos',
  BULK_EDIT_PHOTOS_SUCCESS: 'bulk-edit-photos-success',
  FILEPATHS_OBTAINED: 'filepaths-obtained',
  SELECT_DIRECTORY: 'select-directory',
  SAVE_PHOTO_MANAGER: 'save-photo-manager',
  SAVE_PHOTO_MANAGER_SUCCESS: 'save-photo-manager-success',
  UPDATE_PHOTO_DATA: 'update-photo-data',
  UPDATE_PHOTO_DATA_COMPLETE: 'update-photo-data-complete',
  CREATE_PERSON: 'create-person',
  CREATE_PERSON_SUCCESS: 'create-person-success',
  UPDATE_PERSON: 'update-person',
  UPDATE_PERSON_SUCCESS: 'update-person-success',
  DELETE_PERSON: 'delete-person',
  DELETE_PERSON_SUCCESS: 'delete-person-success',
  BULK_DELETE_PHOTOS: 'delete-photos',
  BULK_DELETE_PHOTOS_SUCCESS: 'delete-photos-success',
  SCRUB_EXIF_DATA: 'scrub-exif-data',
  SCRUB_EXIF_DATA_SUCCES: 'scrub-exif-data-success',
  SELECT_MOVE_TARGET: 'select-move-target',
  SELECT_MOVE_TARGET_SUCCESS: 'select-move-target-success',
  SELECT_MOVE_TARGET_FAILURE: 'select-move-target-failure',
  MOVE_FILES: 'move-files',
  MOVE_FILES_SUCCESS: 'move-files-success',
};

export default null;
